### ISSUE TITLE
Proper naming: homebridge-thermostat-netaTmo + questions

### ISSUE THREAD

**Issue by Siri4Eden** [danpoltawski/homebridge-thermostat-netatmo#1]
Thank you for this great implementation which supports the Apple Home app! 
1. Do you have any plans for merging it into [https://github.com/planetk/homebridge-netatmo](url) by @planetk? (Using your accessory plugin and the netatmo platform plugin together, works also nicely!)
2. Is it possible to set an temperature interval (e.g. 1 degree or configurable) for having Siri "make it warmer/cooler"/"increase/decrease temperature" not jumping to the (almost) max temperatures? (same happens in platform implementation)
3. Proper naming would help with finding/installing your plugin ;-)

**Comment by danpoltawski** [comment]
Hi,

Thanks for looking at it!

1. To be honest, I was finding it really difficult to understand how homebridge plugins worked, so I did try homebridge-netatmo and would've tried to 'fix it' there - but I had to strip everything down to basics to try and help me understand how it was all put together, which is why I ended up creating this plugin. Now I have a better understanding of it I might be able to integrate it (though I don't have much motivation for this right now because of having to this into a 'working' state and only the one thermostat).

2. Hmm. You can do this in the home app - just tap on the thermostat and you get the themostat slider thing to set the temperature and you can ask siri to set the temperature to 'x degrees'. I spent quite a lot of time trying to work out what the best way to map the various homekit behaviours with the netatmo platform. What would you propose? That pressing heat just tries to raise a few degrees above the ambient temp?

3. Wow, thanks. I will fix this shortly! How did you find it? I only created the plugin last weekend! :)

**Comment by Siri4Eden** [comment]
Hi,

ad 1. Understood, anyway thanks for this cool plugin! I disabled the thermostat in the platform and will keep on using yours, very happy with it! :-)

ad 2. Home app GUI behaviour looks perfect. However I am into trying to figure out the VUI/Siri potential - which frustratingly is hardly documented by apple - so I tested it a bit more now:

a. **"Set temperature to x degrees"** works perfectly!
b. **"Increase/Decrease temperature by x degrees"** takes the actual temperature as reference and works nicely. Alternatively one can say **"Make it warmer/cooler by x degrees"**, very nice!
c. **"Make it warmer/cooler"** jumps 5 degrees Celsius up/down, which makes no sense. I guess it comes from Siri being stuck on US centric Fahrenheit (5 F are around 2,6 C, which make more sense) and we cannot do anything about this Siri bug (happens with UK Siri as well).
d. Ecobee has indicated a couple more Siri thermostat commands here: [https://www.ecobee.com/faq/what-voice-commands-can-i-use-to-control-my-homekit-enabled-ecobee3/](url) like:
- **"I'm leaving"** automatically turning thermostat into away mode or 
- **"Good night"** into sleep mode (which is no concept in Netatmo, I guess) as well as 
- **"Good morning"** or **"I'm home"** triggering an home mode, which we do not have.
We could try to trigger those by adding the thermostat to the scenes with the temperatures (but those would only be manual set points I guess, lasting for the specified amount of time. 

I will leave it programmed as heating periods as they currently are and trigger away in the netatmo app (unless you could do some magic with the away mode?)
There seems to be a little bug somewhere when you use the thermostat in a scene: when setting it to 18 C it works fine, when setting it to 23 C it strangely jumps to MAX temperature on the thermostat display. This is just for info, in case you would like to use it in a scene.

ad 3. I stumbled over your plugin by browsing [https://www.npmjs.com/browse/keyword/homebridge-plugin](url) where it is fortunately listed ;-)

Thanks again for the great work!!!

**Comment by danpoltawski** [comment]
> (unless you could do some magic with the away mode?)

What i've done for this is to use the home app to do an automation to which turns it off (i have made _off_ map to _away_ mode). However, it's possible that i'm missing some Characteristic which implements this more naturally. It would be good if you know of any other homebridge accessories which implement this?

**Comment by danpoltawski** [comment]
I have fixed the naming issue - unfortunately you'll have to rename your dependency and config file, but I figured not many people are expected. 

Could I ask you to create an issue about your second point? It would be useful to have an issue tracking it, even if there isn't an obvious fix.

**Comment by Siri4Eden** [comment]
1. Regarding "away": I understand now better what is meant by mapping  Netatmo thermostat modes to HomeKit characteristics (sorry, Newbie). I found https://github.com/KraigM/homebridge-nest/blob/master/index.js implementing "Away" for Nest. I am sure "Away" works for Ecobee3 native HK implementation, however I am not sure how this could be implemented for Netatmo. From the HomeKit Accessory Simulator I see that Custom Characteristics could be added (I guess thats the Nest approach). I don't know if the Custom Characteristics UUID (as hardcoded in Nest) is vendor, apple specific or can be anything ...

2. Regarding setting temp to 23 jumping to Max temp, this is not reproducible anymore in your updated package.

Just let me know what you mean by "create an issue about your second point" and I am happy to do so!
