### ISSUE TITLE
This looks like fun.

### ISSUE THREAD

**Issue by lukewakeford** [danpoltawski/homebridge-thermostat-netatmo#2]
Hey I want to try and use this plugin with my 'MiGo' - Hotpoint rebranded Netatmo thermostat.
Just wondered if anyone had tried this before, I've setup a new app and a user for HomeBridge so will give this a go when I'm home later.

Any pointers appreciated.

✌️

**Comment by danpoltawski** [comment]
Given it talks to the netatmo API, i'm not sure if this would work - it depends if hotpoint use the same infrastructure.

**Comment by lukewakeford** [comment]
I gave it a try. The hotpoint portal is virtually identical but it is a different gateway that doesn't appear to have any developer tools, so I can't create an app in order to gain an id and secret.

Never-mind eh 😭

**Comment by lukewakeford** [comment]
Just realised i meant glow worm not hot point. 🤦‍♂️
